# Generated by Django 5.0.6 on 2024-06-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='essay_type',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatatime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=60, null=True)),
            ],
            options={
                'db_table': 'essay_type',
            },
        ),
        migrations.CreateModel(
            name='essay',
            fields=[
                ('essayid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60, null=True)),
                ('content', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatatime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=60, null=True)),
                ('typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.essay_type')),
            ],
            options={
                'db_table': 'essay',
            },
        ),
    ]
