# Generated by Django 5.0.6 on 2024-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='remark',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='essay_type',
            name='remark',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
