# Generated by Django 5.0.6 on 2024-06-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_alter_essay_remark_alter_essay_type_remark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='updatatime',
            new_name='updatetime',
        ),
        migrations.RenameField(
            model_name='essay_type',
            old_name='updatatime',
            new_name='updatetime',
        ),
        migrations.AddField(
            model_name='essay',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='essay_type',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
