# Generated by Django 5.0.6 on 2024-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_rename_typeid_essay_typedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='side',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
            ],
            options={
                'db_table': 'side',
            },
        ),
    ]
