# Generated by Django 5.0.6 on 2024-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('show', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updatatime', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
