# Generated by Django 5.0.6 on 2024-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remark',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
