# Generated by Django 5.0.6 on 2024-06-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='remark',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
