# Generated by Django 5.0.6 on 2024-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='show',
            field=models.TextField(blank=True, null=True),
        ),
    ]
