# Generated by Django 5.0.6 on 2024-06-27 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_user_name_remove_user_pwd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserMsg',
        ),
        migrations.AlterModelTable(
            name='usermsg',
            table='user_msg',
        ),
    ]
