# Generated by Django 5.0.6 on 2024-06-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_user_usermsg_alter_usermsg_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermsg',
            old_name='updatatime',
            new_name='updatetime',
        ),
    ]
